version: "3.3"
services:
  fetch-ext-ip-addr:
    image: fetch-ext-ip-addr:1.0
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    configs:
     - dns-updater-conf
    networks:
     - updater-net
  update-dns-server:
    image: update-dns-server:1.0
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    networks:
      - updater-net
    configs:
      - dns-updater-conf
    secrets:
      - aws-credentials
  main:
    image: main:1.0
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    networks:
      - updater-net
    configs:
      - dns-updater-conf
  redis:
    image: redis
    deploy:
      placement:
        constraints: [node.role == manager]
    command: redis-server --appendonly yes
    networks:
      - updater-net
networks:
  updater-net:
configs:
  dns-updater-conf:
    file: ./dns-updater.conf
secrets:
  aws-credentials:
    external: true