- hosts: helga
  vars:
    local_cwd: ./
  tasks:

    #
    # Build and install python libmh
    #
    
    # create python wheel locally from sources
    - name: build libmh python egg
      local_action: command /usr/bin/python setup.py bdist_wheel
      args:
        chdir: "{{ local_cwd }}../libmh"

    # get file name of wheel
    - name: get wheel filename
      local_action: shell find ./../libmh -name *.whl -type f -printf "%f\n"
      register: find
    - debug: var=find.stdout_lines[0]

    # copy python wheel to target
    - name: copy libmh wheel to remote
      become: yes
      become_user: mh
      copy:
        src: "{{ local_cwd }}../libmh/dist/{{ find.stdout_lines[0] }}"
        dest: /tmp/

    # install egg on target
    - name: install libmh wheel on target
      become: yes
      command: pip install /tmp/{{ find.stdout_lines[0] }}
