#
# Install and run Python Flask API process
#

- hosts: helga
  tasks:

    # Copy API executable
    - name: copy mh-tracerbn-api.py to remote
      become: yes
      become_user: mh
      copy:
        src: ../raspi/mh-tracerbn-api.py
        dest: /opt/mh/bin/

    # Copy TracerBN driver
    - name: copy mhtracerbn.py to remote
      become: yes
      become_user: mh
      copy:
        src: ../raspi/mhtracerbn.py
        dest: /opt/mh/bin/

    # Restart api process using supervisord
    - name: restart api process
      become: yes
      supervisorctl:
        name: api
        state: restarted