#
# Install all conf required to run MontorHome
#

- hosts: helga
  vars:
      mh_dir: /opt/mh/
  tasks:
    # Create directory structure
    - name: Create {{ mh_dir }} dir structure
      become: yes 
      file:
        path: "{{  mh_dir  }}{{  item  }}"
        state: directory
        owner: mh
        group: mh
      with_items:
        - ['bin', 'db', 'log', 'run', 'keys']
    
    # Copy sqlite3 DB init script
    - name: copy sqlite3 DB init script
      become: yes
      become_user: mh 
      copy:
        src: ../db/create_client_sqlite3_db.sql
        dest: "{{  mh_dir  }}db/"

    # Find any running flask processes
    - name: Get running Python Flask processes
      become: yes
      shell: "supervisorctl status | awk '{print $1}'"
      register: running_processes

    # Stop running process(es) (api)
    - name: stop any running mh processes
      become: yes
      supervisorctl:
        name: "{{ item }}"
        state: stopped
      with_items: "{{ running_processes.stdout_lines }}"

    # TODO: Setup DB using init script
    #- name: Initialise sqlite3 DB
    #  become: yes
    #  become_user: mh
    #  command: sqlite3 -init /opt/mh/db/create_client_sqlite3_db.sql /opt/mh/db/data.db

    # Copy montorhome api supervisor configuration file
    - name: copy supervisor Flask API configuration file to host
      become: yes
      copy:
        src: ../raspi/init/conf/mh_api_supervisor.conf
        dest: /etc/supervisor/conf.d/

    # Copy montorhome api logrotate configuration file
    - name: copy logrotate API configuration file to host
      become: yes
      copy:
        src: ../raspi/init/conf/mh_api_supervisor.conf
        dest: /etc/logrotate/conf.d/

