- hosts: helga
  become: yes
  tasks:

    #
    # Configure hostname
    #
    - name: set hostname to helga
      hostname:
        name: "helga"

    #
    # Configure users
    #
    - name: create user 'mh', add to group 'dialout'
      user:
        name: mh
        comment: MontorHome application user
        groups: dialout
 
    #
    # Configure RPi Locale
    #
    - name: set timezone
      timezone:
        name: "GB" 

    #
    # Configure packages
    #
    - name: Update package cache and upgrade existing packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install supervisord package
      apt:
        name: supervisor

    # Python modules #
    - name: Install python-pip package
      apt:
        name: python-pip

    #
    # Configure SSH login to be keys only
    #
    - name: Disallow password authentication
      lineinfile: dest=/etc/ssh/sshd_config
                  regexp="^PasswordAuthentication"
                  line="PasswordAuthentication no"
                  state=present
      notify: Restart ssh

  handlers:
    - name: Restart ssh
      service: name=ssh state=restarted

